"""add FK indexes

Revision ID: 605daba23479
Revises: 0001
Create Date: 2026-08-15 08:03:04.442265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605daba23479'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analysis_jobs_snapshot_id'), 'analysis_jobs', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_artifacts_snapshot_id'), 'artifacts', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_components_created_by'), 'components', ['created_by'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_components_project_id'), 'components', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_decision_alternatives_decision_id'), 'decision_alternatives', ['decision_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_decision_links_decision_id'), 'decision_links', ['decision_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_decisions_author_user_id'), 'decisions', ['author_user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_dna_scores_snapshot_id'), 'dna_scores', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_event_artifacts_artifact_id'), 'event_artifacts', ['artifact_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_event_artifacts_event_id'), 'event_artifacts', ['event_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_event_components_component_id'), 'event_components', ['component_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_event_components_event_id'), 'event_components', ['event_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_experiment_links_experiment_id'), 'experiment_links', ['experiment_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_exports_snapshot_id'), 'exports', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_file_changes_file_id'), 'file_changes', ['file_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_file_changes_snapshot_id'), 'file_changes', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_files_snapshot_id'), 'files', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_graph_edges_project_id'), 'graph_edges', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_graph_nodes_project_id'), 'graph_nodes', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_graph_nodes_snapshot_id'), 'graph_nodes', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_llm_runs_snapshot_id'), 'llm_runs', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_metric_values_snapshot_id'), 'metric_values', ['snapshot_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_outcome_reviews_author_user_id'), 'outcome_reviews', ['author_user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_outcome_reviews_decision_id'), 'outcome_reviews', ['decision_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_project_memberships_project_id'), 'project_memberships', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_project_memberships_user_id'), 'project_memberships', ['user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_repository_snapshots_project_id'), 'repository_snapshots', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_score_evidence_metric_value_id'), 'score_evidence', ['metric_value_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_score_evidence_score_id'), 'score_evidence', ['score_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_timeline_events_snapshot_id'), 'timeline_events', ['snapshot_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_snapshot_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_score_evidence_score_id'), table_name='score_evidence')
    op.drop_index(op.f('ix_score_evidence_metric_value_id'), table_name='score_evidence')
    op.drop_index(op.f('ix_repository_snapshots_project_id'), table_name='repository_snapshots')
    op.drop_index(op.f('ix_project_memberships_user_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_project_memberships_project_id'), table_name='project_memberships')
    op.drop_index(op.f('ix_outcome_reviews_decision_id'), table_name='outcome_reviews')
    op.drop_index(op.f('ix_outcome_reviews_author_user_id'), table_name='outcome_reviews')
    op.drop_index(op.f('ix_metric_values_snapshot_id'), table_name='metric_values')
    op.drop_index(op.f('ix_llm_runs_snapshot_id'), table_name='llm_runs')
    op.drop_index(op.f('ix_graph_nodes_snapshot_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_project_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_project_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_index(op.f('ix_files_snapshot_id'), table_name='files')
    op.drop_index(op.f('ix_file_changes_snapshot_id'), table_name='file_changes')
    op.drop_index(op.f('ix_file_changes_file_id'), table_name='file_changes')
    op.drop_index(op.f('ix_exports_snapshot_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiment_links_experiment_id'), table_name='experiment_links')
    op.drop_index(op.f('ix_event_components_event_id'), table_name='event_components')
    op.drop_index(op.f('ix_event_components_component_id'), table_name='event_components')
    op.drop_index(op.f('ix_event_artifacts_event_id'), table_name='event_artifacts')
    op.drop_index(op.f('ix_event_artifacts_artifact_id'), table_name='event_artifacts')
    op.drop_index(op.f('ix_dna_scores_snapshot_id'), table_name='dna_scores')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_author_user_id'), table_name='decisions')
    op.drop_index(op.f('ix_decision_links_decision_id'), table_name='decision_links')
    op.drop_index(op.f('ix_decision_alternatives_decision_id'), table_name='decision_alternatives')
    op.drop_index(op.f('ix_components_project_id'), table_name='components')
    op.drop_index(op.f('ix_components_created_by'), table_name='components')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_artifacts_snapshot_id'), table_name='artifacts')
    op.drop_index(op.f('ix_analysis_jobs_snapshot_id'), table_name='analysis_jobs')
    # ### end Alembic commands ###