export function MethodologyPage() {
  const dimensions = [
    { key: "technical_complexity", name: "Technical Complexity", direction: "Descriptive", desc: "Number and interaction of technical elements." },
    { key: "maintainability", name: "Maintainability", direction: "Higher is better", desc: "Hotspot dispersion, file-size health, coupling, test maturity, docs." },
    { key: "testing_maturity", name: "Testing Maturity", direction: "Higher is better", desc: "Test-file ratio, CI test signal, breadth, recency. Not a coverage claim." },
    { key: "documentation_quality", name: "Documentation Quality", direction: "Higher is better", desc: "README completeness, setup, ADRs, API docs, governance." },
    { key: "evolution_health", name: "Evolution Health", direction: "Higher is better", desc: "Traceable changes, releases, controlled change size, rationale, follow-up." },
    { key: "delivery_readiness", name: "Delivery Readiness", direction: "Higher is better", desc: "Automated checks, env separation, lockfiles, deployment, release/rollback." },
    { key: "scalability_readiness", name: "Scalability Readiness", direction: "Higher is better", desc: "Separation of concerns, data discipline, statelessness, async, observability." },
    { key: "technical_debt_risk", name: "Technical Debt Risk", direction: "Lower is better", desc: "Hotspot concentration, rework, test gaps, markers, doc gaps, config risk." },
  ];

  return (
    <div>
      <h1 className="mb">Scoring Methodology</h1>
      <p className="muted mb">
        Model <code>dna-core-1.0</code>. Scores are generated by code, not by an LLM. Raw indicators are
        retained for reproducibility.
      </p>

      <h2 className="mb">General formula</h2>
      <pre className="code">{`score(d) = round(100 × Σ(wᵢ × qᵢ × xᵢ) / Σ(wᵢ × qᵢ))
coverage(d) = Σ(wᵢ × qᵢ) / Σ(wᵢ)`}</pre>
      <p className="muted small">
        xᵢ = normalized indicator in [0,1], wᵢ = weight, qᵢ = evidence-quality factor. The denominator
        only includes available evidence. Coverage is displayed separately so a high score from thin
        evidence is not mistaken for a strong conclusion.
      </p>

      <h2 className="mt-lg mb">Confidence labels</h2>
      <table>
        <thead>
          <tr>
            <th>Coverage</th>
            <th>Label</th>
          </tr>
        </thead>
        <tbody>
          <tr><td>&lt; 0.35</td><td>Insufficient evidence — score withheld</td></tr>
          <tr><td>0.35 – 0.59</td><td>Low confidence</td></tr>
          <tr><td>0.60 – 0.79</td><td>Moderate confidence</td></tr>
          <tr><td>0.80 – 1.00</td><td>High confidence</td></tr>
        </tbody>
      </table>

      <h2 className="mt-lg mb">Dimensions</h2>
      <div className="grid grid-2">
        {dimensions.map((d) => (
          <div key={d.key} className="card">
            <div className="row between">
              <h3 style={{ margin: 0 }}>{d.name}</h3>
              <span className="badge accent">{d.direction}</span>
            </div>
            <p className="muted small mt">{d.desc}</p>
          </div>
        ))}
      </div>

      <h2 className="mt-lg mb">Caveats</h2>
      <ul className="muted">
        <li>Scores are descriptive evidence-weighted signals, not quality verdicts.</li>
        <li>Technical Debt Risk is "lower is better".</li>
        <li>A dimension with inadequate coverage is withheld, never scored as zero.</li>
        <li>Testing Maturity is not a claim about actual test coverage.</li>
        <li>LLM output is evidence-grounded and never used for scoring.</li>
      </ul>
    </div>
  );
}